version: "3"
services:
  api-db:
    image: postgres
    environment:
      POSTGRES_DB: marttech-test
      POSTGRES_PASSWORD: precisa_mudar_isso_aqui
  api:
    depends_on:
      - api-db
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
